default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: admin
  password: admin
  host: localhost
  port: 15432

development:
  <<: *default
  database: dev_auctioneer

test:
  <<: *default
  database: test_auctioneer

production:
  <<: *default
  database: auctioneer