Race.create!(id: 1, mask: 1, side: 'alliance', name: 'Human')
Race.create!(id: 2, mask: 2, side: 'horde', name: 'Orc')
Race.create!(id: 3, mask: 4, side: 'alliance', name: 'Dwarf')
Race.create!(id: 4, mask: 8, side: 'alliance', name: 'Night Elf')
Race.create!(id: 5, mask: 16, side: 'horde', name: 'Undead')
Race.create!(id: 6, mask: 32, side: 'horde', name: 'Tauren')
Race.create!(id: 7, mask: 64, side: 'alliance', name: 'Gnome')
Race.create!(id: 8, mask: 128, side: 'horde', name: 'Troll')
Race.create!(id: 9, mask: 256, side: 'horde', name: 'Goblin')
Race.create!(id: 10, mask: 512, side: 'horde', name: 'Blood Elf')
Race.create!(id: 11, mask: 1024, side: 'alliance', name: 'Draenei')
Race.create!(id: 22, mask: 2097152, side: 'alliance', name: 'Worgen')
Race.create!(id: 24, mask: 8388608, side: 'neutral', name: 'Pandaren')
Race.create!(id: 25, mask: 16777216, side: 'alliance', name: 'Pandaren')
Race.create!(id: 26, mask: 33554432, side: 'horde', name: 'Pandaren')

Clazz.create!(id: 1, mask: 1, power_type: 'rage', name: 'Warrior')
Clazz.create!(id: 2, mask: 2, power_type: 'mana', name: 'Paladin')
Clazz.create!(id: 3, mask: 4, power_type: 'focus', name: 'Hunter')
Clazz.create!(id: 4, mask: 8, power_type: 'energy', name: 'Rogue')
Clazz.create!(id: 5, mask: 16, power_type: 'mana', name: 'Priest')
Clazz.create!(id: 6, mask: 32, power_type: 'runic-power', name: 'Death Knight')
Clazz.create!(id: 7, mask: 64, power_type: 'mana', name: 'Shaman')
Clazz.create!(id: 8, mask: 128, power_type: 'mana', name: 'Mage')
Clazz.create!(id: 9, mask: 256, power_type: 'mana', name: 'Warlock')
Clazz.create!(id: 10, mask: 512, power_type: 'energy', name: 'Monk')
Clazz.create!(id: 11, mask: 1024, power_type: 'mana', name: 'Druid')
Clazz.create!(id: 12, mask: 2048, power_type: 'fury', name: 'Demon Hunter')